trigger:
- none

name: Deploy Agent Installation Automation

pool: IRRNDG-AUTOMATION-POOL

parameters:
  - name: agentInstallationAutomation
    displayName: 'Choose an agent installation scope:'
    type: string
    default: Virtual Machine - Install agent on a virtual machine
    values:
      - Virtual Machine - Install agent on a virtual machine
      - Resource Group - Install agent throughout all virtual machines found in a resource group
      - Tag - Install agent throughout all virtual machines with a given tag found in a resource group

stages:
  - ${{ if eq(parameters.agentInstallationAutomation, 'Virtual Machine - Install agent throughout a virtual machine' ) }}:
    - template: virtual-machine-installation.yml
    
  - ${{ if eq(parameters.agentInstallationAutomation, 'Resource Group - Install agent throughout all virtual machines found in a resource group' ) }}:
    - template: resource-group-installation.yml
  
  - ${{ if eq(parameters.agentInstallationAutomation, 'Tag - Install agent throughout all virtual machines with a given tag found in a resource group' ) }}:
    - template: tag-installation.yml