trigger: none

parameters:
  - name: username
    type: string

variables:
  - group: SERVER-ONBOARDING-VARS

stages:
- stage: ServerOnboardingStage
  jobs:
  - job: AgentInstallationJob
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: CopyFiles@2
        displayName: Copy Run Command Scripts to Virtual Machine
        inputs:
          sourceFolder: $(System.DefaultWorkingDirectory)/scripts/run-commands
          targetFolder: C:/scripts/ServerOnboardingAutomation
          overWrite: true

      - task: PowerShell@2
        displayName: Authenticate with ADM Account
        inputs:
          targetType: inline
          script: |
            az logout --username ${{ parameters.username }}
            az account clear
            az login -u ${{ parameters.username }} -p $(${{ parameters.username }})

      - task: PowerShell@2
        displayName: Onboard Virtual Machines
        inputs:
          targetType: filePath
          filePath: $(System.DefaultWorkingDirectory)/scripts/ProcessCsvData.ps1