trigger: none

pool: IRRNDG-AUTOMATION-POOL

parameters:
  - name: username
    displayName: Username
    type: string
  - name: hasServerInformationExport
    displayName: Export Server Information
    type: boolean
    default: false
  - name: hasServerOnboarding
    displayName: Perform Server Onboarding
    type: boolean
    default: true
  - name: hasPowerStateCycling
    displayName: Perform Power State Cycling
    type: boolean
    default: false

variables:
  - group: SERVER-ONBOARDING-VARS
  - ${{ if eq(parameters['hasServerInformationExport'], 'true') }}:
    - name: hasServerInformationExport
      value: $true
  - ${{ else }}:
    - name: hasServerInformationExport
      value: $false
  - ${{ if eq(parameters['hasServerOnboarding'], 'true') }}:
    - name: hasServerOnboarding
      value: $true
  - ${{ else }}:
    - name: hasServerOnboarding
      value: $false
  - ${{ if eq(parameters['hasPowerStateCycling'], 'true') }}:
    - name: hasPowerStateCycling
      value: $true
  - ${{ else }}:
    - name: hasPowerStateCycling
      value: $false

stages:
- stage: AzureAuthenticationStage
  jobs:
  - job: AzureAuthenticationJob
    steps:
      - task: PowerShell@2
        displayName: Authenticate with ADM Account
        inputs:
          targetType: inline
          script: |
            az login -u ${{ parameters.username }} -p $(${{ parameters.username }})

- stage: ServerInformationExportStage
  dependsOn: AzureAuthenticationStage
  condition: eq('${{ parameters.hasServerInformationExport }}', 'true')
  jobs:
  - job: ServerInformationExportJob
    steps:
      - task: PowerShell@2
        displayName: Export Virtual Machine Information
        inputs:
          targetType: inline
          script: |
            Write-Host "Hello world"

- stage: ServerOnboardingStage
  dependsOn: AzureAuthenticationStage
  condition: eq('${{ parameters.hasServerOnboarding }}', 'true')
  jobs:
  - job: ServerOnboardingJob
    steps:
      - task: CopyFiles@2
        displayName: Copy Run Command Scripts to Virtual Machine
        inputs:
          sourceFolder: $(System.DefaultWorkingDirectory)/scripts/runCommands
          targetFolder: C:/scripts/ServerOnboardingAutomation
          overWrite: true

      - task: PowerShell@2
        displayName: Perform Server Onboarding
        inputs:
          targetType: filePath
          filePath: $(System.DefaultWorkingDirectory)/scripts/ProcessCsvData.ps1
          arguments: >
            -hasServerInformationExport ${{ variables.hasServerInformationExport }} 
            -hasServerOnboarding ${{ variables.hasServerOnboarding }} 
            -hasPowerStateCycling ${{ variables.hasPowerStateCycling }} 