trigger: none

parameters:
  - name: username
    type: string

variables:
  - group: SERVER-ONBOARDING-VARS

stages:
- stage: ServerOnboardingStage
  jobs:
  - job: AgentInstallationJob
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Run Command Scripts to Virtual Machine'
        inputs:
          sourceFolder: "$(System.DefaultWorkingDirectory)/scripts/run-commands"
          targetFolder: "C:/scripts/ServerOnboardingAutomation"
          overWrite: true

      - task: AzureCLI@2
        displayName: Authenticate with ADM Account
        inputs:
          azureSubscription: ICO-DEV-SERVICE-CONN
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            az account clear
            az login -u ${{ parameters.username }} -p $(${{ parameters.username }})

      - task: AzureCLI@2
        displayName: 'Onboard Virtual Machines'
        inputs:
          azureSubscription: ICO-DEV-SERVICE-CONN
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/ProcessCsvData.ps1'