trigger: none

pool: IRRNDG-AUTOMATION-POOL

parameters:
  - name: Username
    type: string
  - name: hasVMInformationExport
    displayName: Export Virtual Machine Information
    type: boolean
    default: false
  - name: hasServerOnboarding
    displayName: Perform Server Onboarding
    type: boolean
    default: true
  - name: hasPowerStateCycling
    displayName: Perform Power State Cycling (modify only if 'Perform Server Onboarding' is true)
    type: boolean
    default: false

variables:
  - group: SERVER-ONBOARDING-VARS

stages:
- stage: AzureAuthentication
  jobs:
  - job: AzureAuthentication
    steps:
      - task: PowerShell@2
        displayName: Authenticate with ADM Account
        inputs:
          targetType: inline
          script: |
            az login -u ${{ parameters.username }} -p $(${{ parameters.username }})

- stage: VMInformationExport
  dependsOn: AzureAuthentication
  condition: eq('${{ parameters.hasVMInformationExport }}', 'true')
  jobs:
  - job: VMInformationExport
    steps:
      - task: PowerShell@2
        displayName: Export Virtual Machine Information
        inputs:
          targetType: inline
          script: |
            Write-Host "Hello world"

- stage: ServerOnboarding
  dependsOn: AzureAuthentication
  condition: eq('${{ parameters.hasServerOnboarding }}', 'true')
  jobs:
  - job: ServerOnboarding
    steps:
      - task: CopyFiles@2
        displayName: Copy Run Command Scripts to Virtual Machine
        inputs:
          sourceFolder: $(System.DefaultWorkingDirectory)/scripts/runCommands
          targetFolder: C:/scripts/ServerOnboardingAutomation
          overWrite: true

      - task: PowerShell@2
        displayName: Perform Server Onboarding
        inputs:
          targetType: filePath
          filePath: $(System.DefaultWorkingDirectory)/scripts/ServerOnboarding.ps1 -hasPowerStateCycling {{ parameters.hasPowerStateCycling }}