parameters:
  - name: subscription
    type: string
  - name: resourceGroup
    type: string
  - name: workspaceId
    type: string
  - name: workspaceKey
    type: string

stages:
- stage: Build
  displayName: Install Agent by Resource Group
  jobs:
  - job: Build
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: AzureCLI@2
        displayName: 'Install Agent by Resource Group'
        inputs:
          azureSubscription: ICO-DEV-SERVICE-CONN
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/InstallMMAByResourceGroup.ps1'
          arguments: '-subscription ${{ parameters.subscription }} -resourceGroup ${{ parameters.resourceGroup }} -workspaceId ${{ parameters.workspaceId }} -workspaceKey ${{ parameters.workspaceKey }}'