trigger: none

parameters:
  - name: subscription
    type: string
  - name: resourceGroup
    type: string
  - name: tagValue
    type: string
  - name: workspaceId
    type: string
  - name: workspaceKey
    type: string

stages:
- stage: Build
  displayName: Install Agent by Tag
  jobs:
  - job: Build
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: AzureCLI@2
        displayName: 'Install Agent by Tag'
        inputs:
          azureSubscription: ICO-DEV-SERVICE-CONN
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/InstallMMAByTagValue.ps1'
          arguments: '-subscription ${{ parameters.subscription }} -resourceGroup ${{ parameters.resourceGroup }} -tagValue ${{ parameters.tagValue }} -workspaceId ${{ parameters.workspaceId }} -workspaceKey ${{ parameters.workspaceKey }}'