trigger: none

parameters:
  - name: subscription
    type: string
  - name: resourceGroup
    type: string
  - name: virtualMachineName
    type: string
  - name: workspaceId
    type: string
  - name: workspaceKey
    type: string

stages:
- stage: Build
  displayName: Install Agent by Virtual Machine
  jobs:
  - job: Build
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: AzureCLI@2
        displayName: 'Install Agent by Virtual Machine'
        inputs:
          azureSubscription: ICO-DEV-SERVICE-CONN
          scriptType: pscore
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/InstallMMAByVirtualMachineName.ps1'
          arguments: '-subscription ${{ parameters.subscription }} -resourceGroup ${{ parameters.resourceGroup }} -virtualMachineName ${{ parameters.virtualMachineName }} -workspaceId ${{ parameters.workspaceId }} -workspaceKey ${{ parameters.workspaceKey }}'