parameters:
  - name: azureResourceManagerConnection
    type: string
    default: ICO-DEV-SERVICE-CONN

stages:
- stage: Build
  displayName: Install Agent by Virtual Machine
  jobs:
  - job: Build
    variables:
    - group: AGENT-INSTALLATION-VIRTUAL-MACHINE-VARS
    pool: IRRNDG-AUTOMATION-POOL
    steps:
      - task: AzureCLI@2
        displayName: 'Install Agent by Virtual Machine'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/InstallMMAByVirtualMachineName.ps1'
          arguments: '-subscription $(subscription) -resourceGroup $(resourceGroup) -virtualMachineName $(virtualMachineName) -workspaceId $(workspaceId) -workspaceKey $(workspaceKey)'